version: "3.8"
services:
  dbt_postgres_eia_service:
    image: postgres:16
    container_name: dbt-postgres-eia
    environment:
      POSTGRES_USER: ${DWH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DWH_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DWH_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    networks:
      - default
      - astro_network

volumes:
  pgdata:
  pgdata2:

networks:
  astro_network:
    external: true
    name: ${ASTRO_NETWORK_NAME}