version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: dbt-postgres
    environment:
      POSTGRES_USER: dbtuser
      POSTGRES_PASSWORD: dbtpass
      POSTGRES_DB: dbtdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: