x-dbt-common: &dbt-common
  volumes:
    - ../dbt:/usr/local/airflow/dbt
  environment:
    - DBT_POSTGRES_PASSWORD=${AIRFLOW_VAR_DWH_POSTGRES_PASSWORD}
    - AIRFLOW_CONN_DBT_POSTGRES_EIA=${AIRFLOW_CONN_DBT_POSTGRES_EIA}

services:
  scheduler:
    <<: *dbt-common
  dag-processor:
    <<: *dbt-common
  api-server:
    <<: *dbt-common
  triggerer:
    <<: *dbt-common